name: Build and Test (FFTW Serial Only)

on:
  push:
    branches: [ "main" , "testing"]
  pull_request:
    branches: [ "main" , "testing"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # If one fails, let the others finish
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - compiler: gcc
            cc: gcc
            cxx: g++
          - compiler: clang
            cc: clang
            cxx: clang++

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

        # Install only Serial FFTW and OpenMP (No MPI)
        sudo apt-get install -y libfftw3-dev libomp-dev

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pybind11 setuptools matplotlib

    - name: Compile and Install anyFFT
      run: |
        echo "Using Compiler: $CXX"
        $CXX --version

        # Build verbose to confirm MPI is skipped
        pip install -v .

    - name: Run Test Suite
      run: |
        # This will run only serial FFTW tests.
        # Parallel tests will self-skip because mpi4py is missing.
        anyfft-test